### ISSUE TITLE
Could you leave any contact to you?

### ISSUE THREAD

**Issue by Amejame** [ferguras/twitter-analysis#11]
I wanna talk with you about something regarding to your repo and to do it faster and easier could you please give me any discord/twitter or smth like that to communicate?

**Comment by ferguras** [comment]
You asked for contact details on several different clones of this repo.
Could you plz post the question and I'll try to answer it.

**Comment by Amejame** [comment]
I’m willing to do a twitter monitor that posts every tweet from a user to discord webhook. The thing I care about the most and only is speed of this transfer. I want it to be extremely fast and to send webhooks as soon as possible. As I figured out I should better not use Twitter api to this project because it has some delays on it and for me every millisecond counts. So I thought of using a twitter scraper but there I come to you. Do you have any ideas how to use it in the purpose I wrote above? Or maybe you know how to do it the best way? Any tips or ideas would be lovely

**Comment by ferguras** [comment]
This script may be too complex for your Requirement but you could adapt it. It takes the info from the webpage. The speed limit is your connection although twitter ddos protection might not like it much.
Simply keep on refreshing the webpage as fast as ya want.

**Comment by Amejame** [comment]
I would run it on server anyway. But refreshing the webpage won't give the effect, cause it won't send faster notification to discord as I want it to be. This it the point. Extremely fast and posting webhooks
